  enum DiseaseGroup {
  RESPIRATORY,
  ATRIAL_FIBR,
  CARDIOVASCULAR,
  OSTEOARTHRITIS,
  OSTEOPOROSIS,
  RHEUMATOID,
  MENTAL_HEALTH,
  CANCER,
  DIGESTIVE,
  HYPERTENSION,
  BLOODFATS,
  CHRONIC_KIDNEY,
  DIABETES_TYPE_1,
  DIABETES_TYPE_2,
  VENOUS_THROMBO,
  OTHER
}

export const diseases = [
  {id: 'TRANSIENT_ISCHAEMIC_ATTACK', label: 'Accident ischémique transitoire', group: DiseaseGroup.CARDIOVASCULAR},
  {id: 'ANXIETY', label: 'Anxiete', group: DiseaseGroup.MENTAL_HEALTH},
  {id: 'ASTHMA', label: 'Asthme', group: DiseaseGroup.RESPIRATORY},
  {id: 'STROKE', label: 'AVC', group: DiseaseGroup.CARDIOVASCULAR},
  {id: 'BIPOLAR', label: 'Bipolaire', group: DiseaseGroup.MENTAL_HEALTH},
  {id: 'CANCER', label: 'Cancer', group: DiseaseGroup.CANCER},
  {id: 'CHRONIC_LIVER', label: 'Cirrhose', group: DiseaseGroup.DIGESTIVE},
  {id: 'ULCER_COLITIS', label: 'Colite ulcéreuse', group: DiseaseGroup.DIGESTIVE},
  {id: 'COELIAC', label: 'Coeliaque', group: DiseaseGroup.DIGESTIVE},
  {id: 'COPD', label: 'Copd', group: DiseaseGroup.RESPIRATORY},
  {id: 'DEPRESSION', label: 'Depression', group: DiseaseGroup.MENTAL_HEALTH},
  {id: 'DEMENTIA', label: 'Demence', group: DiseaseGroup.MENTAL_HEALTH},
  {id: 'DIABETES_TYPE_1', label: 'Diabete type 1', group: DiseaseGroup.DIABETES_TYPE_1},
  {id: 'DIABETES_TYPE_2', label: 'Diabete type 2', group: DiseaseGroup.DIABETES_TYPE_2},
  {id: 'EPILEPSY', label: 'Epilepsie', group: DiseaseGroup.OTHER},
  {id: 'ATRIAL_FIBR', label: 'Fibrillation atriale', group: DiseaseGroup.ATRIAL_FIBR},
  {id: 'HYPERCHOLESTEROLAEMIA', label: 'Hypercholestérolémie', group: DiseaseGroup.BLOODFATS},
  {id: 'HYPERLIPIDAEMIA', label: 'Hyperlipémie', group: DiseaseGroup.BLOODFATS},
  {id: 'HYPERTENSION', label: 'Hypertension', group: DiseaseGroup.HYPERTENSION},
  {id: 'HYPERTRIGLYCERIDAEMIA', label: 'Hypertriglycéridémie', group: DiseaseGroup.BLOODFATS},
  {id: 'CONG_HEART_FAILURE', label: 'Insuffisance cardiaque', group: DiseaseGroup.CARDIOVASCULAR},
  {id: 'CORONARY_HEART', label: 'Insuffisance coronarienne', group: DiseaseGroup.CARDIOVASCULAR},
  {id: 'CHRONIC_KIDNEY', label: 'Insuffisance rénale chronique', group: DiseaseGroup.CHRONIC_KIDNEY},
  {id: 'CROHNS', label: 'Maladie de crohns', group: DiseaseGroup.DIGESTIVE},
  {id: 'MALABSORP_SYNDR', label: 'Malabsorption', group: DiseaseGroup.DIGESTIVE},
  {id: 'OSTEOARTHRITIS', label: 'Ostéoarthrite', group: DiseaseGroup.OSTEOARTHRITIS},
  {id: 'OSTEOPOROSIS', label: 'Osteoporose', group: DiseaseGroup.OSTEOPOROSIS},
  {id: 'PANCREATITIS', label: 'Pancréatite', group: DiseaseGroup.DIGESTIVE},
  {id: 'RHEUMATOID', label: 'Rhumatoïde', group: DiseaseGroup.RHEUMATOID},
  {id: 'SCHIZOPHRENIA', label: 'Schyzophrene', group: DiseaseGroup.MENTAL_HEALTH},
  {id: 'STEATORRHEA', label: 'Stéatorrhée', group: DiseaseGroup.DIGESTIVE},
  {id: 'VENOUS_THROMBO', label: 'Thrombose veineuse', group: DiseaseGroup.VENOUS_THROMBO},
  {id: 'RHEUMATIC_HEART', label: 'Valvulopathie cardiaque', group: DiseaseGroup.CARDIOVASCULAR}
];
